[profile.default]
src = "src"
out = "out"
libs = ["lib"]

evm_version = "prague"
via_ir = true

[fmt]
ignore = ["src/SoladyBls.sol"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
