[package]
name = "w3f-ring-proof"
version = "0.0.10"
edition = "2021"
authors = ["Sergey Vasilyev <swasilyev@gmail.com>"]
license = "MIT/Apache-2.0"
description = "zk-proof of knowledge of the blinding factor of a Pedersen commitment"
keywords = ["cryptography", "ring-vrf"]
repository = "https://github.com/w3f/ring-proof"

[dependencies]
w3f-pcs.workspace = true
w3f-plonk-common.workspace = true
ark-transcript.workspace = true
ark-std.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
ark-poly.workspace = true
ark-serialize.workspace = true
rayon = { workspace = true, optional = true }

[dev-dependencies]
ark-bls12-381.workspace = true
ark-ed-on-bls12-381-bandersnatch.workspace = true
criterion.workspace = true

[[bench]]
name = "ring_proof"
harness = false

[features]
default = [ "std" ]
std = [
  "ark-std/std",
  "ark-ff/std",
  "ark-ec/std",
  "ark-poly/std",
  "ark-serialize/std",
  "w3f-pcs/std",
  "w3f-plonk-common/std"
]
parallel = [
  "std",
  "rayon",
  "ark-std/parallel",
  "ark-ff/parallel",
  "ark-ec/parallel",
  "ark-poly/parallel",
  "w3f-plonk-common/parallel",
  "w3f-pcs/parallel"
]
print-trace = ["ark-std/print-trace"]
asm = [ "w3f-pcs/asm" ]
